// Indent=4, tab=4, column width=120, CR/LF, codepage=ASCII
// Original filename: ReadOmf_StringOrdinals.h
// Copyright (C) 2022 David Miller
// This file is part of the Omfoo Source Code Project.
// You should have received a copy of the source code license with this file.
// Please see OMFOO_SOURCECODE_LICENSE.TXT or send inquiries to OmfooGuy@gmail.com.
//*********************************************************************************************************************
#pragma once
class CReadOmf_StringOrdinals
{
protected:

//	OMF Properties.
enum PropOrdinal {
	ePropRev1NoProperty,					// OMFI:NoProperty
	ePropRev1Attributes,					// OMFI:Attributes
	ePropRev1Author,						// OMFI:Author
	ePropRev1Blobs,							// OMFI:Blobs
	ePropRev1ByteOrder,						// OMFI:ByteOrder
	ePropRev1CharacterSet,					// OMFI:CharacterSet
	ePropRev1ClassDictionary,				// OMFI:ClassDictionary
	ePropRev1CompositionMobs,				// OMFI:CompositionMobs
	ePropRev1ContOffsetAtClose,				// OMFI:ContainerOffsetAtClose
	ePropRev1Copyright,						// OMFI:Copyright
	ePropRev1Date,							// OMFI:Date
	ePropRev1DelBlobsSize,					// OMFI:DelBlobsSize
	ePropRev1ExternalFiles,					// OMFI:ExternalFiles
	ePropRev1LastModified,					// OMFI:LastModified
	ePropRev1MediaData,						// OMFI:MediaData
	ePropRev1MinorVersion,					// OMFI:MinorVersion
	ePropRev1NumDelMobs,					// OMFI:NumDelMobs
	ePropRev1ObjectSpine,					// OMFI:ObjectSpine
	ePropRev1ObjID,							// OMFI:ObjID
	ePropRev1SourceMobs,					// OMFI:SourceMobs
	ePropRev1TOCOffsetAtClose,				// OMFI:TOCOffsetAtClose
	ePropRev1ToolkitVersion,				// OMFI:ToolkitVersion
	ePropRev1Version,						// OMFI:Version

	ePropAbob64BitSupport,					// OMFI:ABOB:64BitSupport
	ePropAcptMobID,							// OMFI:ACPT:MobID
	ePropAifcAudioData,						// OMFI:AIFC:AudioData
	ePropAifcData,							// OMFI:AIFC:Data
	ePropAifcDataPos,						// OMFI:AIFC:DataPos
	ePropAifcMobID,							// OMFI:AIFC:MobID
	ePropAifdSummary,						// OMFI:AIFD:Summary
	ePropAtcpAttributes,					// OMFI:ATCP:Attributes
	ePropAttbBobData,						// OMFI:ATTB:BobData
	ePropAttbBobSize,						// OMFI:ATTB:BobSize
	ePropAttbDataAttribute,					// OMFI:ATTB:DataAttribute
	ePropAttbIntAttribute,					// OMFI:ATTB:IntAttribute
	ePropAttbKind,							// OMFI:ATTB:Kind
	ePropAttbName,							// OMFI:ATTB:Name
	ePropAttbObjAttribute,					// OMFI:ATTB:ObjAttribute
	ePropAttbStringAttribute,				// OMFI:ATTB:StringAttribute
	ePropAttrAttrRefs,						// OMFI:ATTR:AttrRefs
	ePropAttrNumItems,						// OMFI:ATTR:NumItems
	ePropBtxtEncoding,						// OMFI:BTXT:Encoding
	ePropCdciAlphaSampledDepth,				// OMFI:CDCI:AlphaSampledDepth
	ePropCdciBlackReferenceLevel,			// OMFI:CDCI:BlackReferenceLevel
	ePropCdciColorRange,					// OMFI:CDCI:ColorRange
	ePropCdciColorSiting,					// OMFI:CDCI:ColorSiting
	ePropCdciComponentWidth,				// OMFI:CDCI:ComponentWidth
	ePropCdciHorizontalSubsampling,			// OMFI:CDCI:HorizontalSubsampling
	ePropCdciIgnoreBWRefLevelAndColorRange,	// OMFI:CDCI:IgnoreBWRefLevelAndColorRange
	ePropCdciOffsetToFrameIndexes,			// OMFI:CDCI:OffsetToFrameIndexes
	ePropCdciPaddingBits,					// OMFI:CDCI:PaddingBits
	ePropCdciVerticalSubsampling,			// OMFI:CDCI:VerticalSubsampling
	ePropCdciWhiteReferenceLevel,			// OMFI:CDCI:WhiteReferenceLevel
	ePropClipLength,						// OMFI:CLIP:Length
	ePropClsdClass,							// OMFI:CLSD:Class
	ePropClsdClassID,						// OMFI:CLSD:ClassID
	ePropClsdParentClass,					// OMFI:CLSD:ParentClass
	ePropCmobDefFadeEditUnit,				// OMFI:CMOB:DefFadeEditUnit
	ePropCmobDefFadeLength,					// OMFI:CMOB:DefFadeLength
	ePropCmobDefFadeType,					// OMFI:CMOB:DefFadeType
	ePropCmpoCreationTime,					// OMFI:CMPO:CreationTime
	ePropCmpoMobID,							// OMFI:CMPO:MobID
	ePropCompParamList,						// OMFI:COMP:ParamList
	ePropCpntAttributes,					// OMFI:CPNT:Attributes
	ePropCpntDataKind,						// OMFI:CPNT:DataKind
	ePropCpntEditRate,						// OMFI:CPNT:EditRate
	ePropCpntEffectID,						// OMFI:CPNT:EffectID
	ePropCpntLeftBob,						// OMFI:CPNT:LeftBob
	ePropCpntLength,						// OMFI:CPNT:Length
	ePropCpntName,							// OMFI:CPNT:Name
	ePropCpntPrecomputed,					// OMFI:CPNT:Precomputed
	ePropCpntRightBob,						// OMFI:CPNT:RightBob
	ePropCpntSessionAttrs,					// OMFI:CPNT:SessionAttrs
	ePropCpntTrackKind,						// OMFI:CPNT:TrackKind
	ePropCpntUserAttributes,				// OMFI:CPNT:UserAttributes
	ePropCtlpDataKind,						// OMFI:CTLP:DataKind
	ePropCtlpEditHint,						// OMFI:CTLP:EditHint
	ePropCtlpPointProperties,				// OMFI:CTLP:PointProperties
	ePropCtlpTime,							// OMFI:CTLP:Time
	ePropCtlpValue,							// OMFI:CTLP:Value
	ePropCvalParameterID,					// OMFI:CVAL:ParameterID
	ePropCvalValue,							// OMFI:CVAL:Value
	ePropDdefDataKindID,					// OMFI:DDEF:DataKindID
	ePropDiddAlphaTransparency,				// OMFI:DIDD:AlphaTransparency
	ePropDiddAMEVersion,					// OMFI:DIDD:AMEVersion
	ePropDiddClientFillEnd,					// OMFI:DIDD:ClientFillEnd
	ePropDiddClientFillStart,				// OMFI:DIDD:ClientFillStart
	ePropDiddCompression,					// OMFI:DIDD:Compression
	ePropDiddDataOffset,					// OMFI:DIDD:DataOffset
	ePropDiddDIDCompressMethod,				// OMFI:DIDD:DIDCompressMethod
	ePropDiddDIDDFirstFrameOffset,			// OMFI:DIDD:DIDDFirstFrameOffset
	ePropDiddDIDDFrameSampleSize,			// OMFI:DIDD:DIDDFrameSampleSize
	ePropDiddDIDDImageSize,					// OMFI:DIDD:DIDDImageSize
	ePropDiddDIDImageSize,					// OMFI:DIDD:DIDImageSize
	ePropDiddDIDResolutionID,				// OMFI:DIDD:DIDResolutionID
	ePropDiddDisplayHeight,					// OMFI:DIDD:DisplayHeight
	ePropDiddDisplayWidth,					// OMFI:DIDD:DisplayWidth
	ePropDiddDisplayXOffset,				// OMFI:DIDD:DisplayXOffset
	ePropDiddDisplayYOffset,				// OMFI:DIDD:DisplayYOffset
	ePropDiddFirstFrameOffset,				// OMFI:DIDD:FirstFrameOffset
	ePropDiddFrameIndexByteOrder,			// OMFI:DIDD:FrameIndexByteOrder
	ePropDiddFrameLayout,					// OMFI:DIDD:FrameLayout
	ePropDiddFrameSampleSize,				// OMFI:DIDD:FrameSampleSize
	ePropDiddFrameStartOffset,				// OMFI:DIDD:FrameStartOffset
	ePropDiddGamma,							// OMFI:DIDD:Gamma
	ePropDiddImageAlignmentFactor,			// OMFI:DIDD:ImageAlignmentFactor
	ePropDiddImageAspectRatio,				// OMFI:DIDD:ImageAspectRatio
	ePropDiddNextDIDDesc,					// OMFI:DIDD:NextDIDDesc
	ePropDiddNextDIDDescriptor,				// OMFI:DIDD:NextDIDDescriptor
	ePropDiddOffsetToRLEFrameIndexes,		// OMFI:DIDD:OffsetToRLEFrameIndexes
	ePropDiddSampledHeight,					// OMFI:DIDD:SampledHeight
	ePropDiddSampledWidth,					// OMFI:DIDD:SampledWidth
	ePropDiddSampledXOffset,				// OMFI:DIDD:SampledXOffset
	ePropDiddSampledYOffset,				// OMFI:DIDD:SampledYOffset
	ePropDiddStoredHeight,					// OMFI:DIDD:StoredHeight
	ePropDiddStoredWidth,					// OMFI:DIDD:StoredWidth
	ePropDiddUniformness,					// OMFI:DIDD:Uniformness
	ePropDiddVideoLineMap,					// OMFI:DIDD:VideoLineMap
	ePropDiddVideoLineMapSize,				// OMFI:DIDD:VideoLineMapSize
	ePropDlPathName,						// OMFI:DL:PathName
	ePropDoslPathName,						// OMFI:DOSL:PathName
	ePropEccpAvidFilmKind,					// OMFI:ECCP:AvidFilmKind
	ePropEccpCodeFormat,					// OMFI:ECCP:CodeFormat
	ePropEccpFilmKind,						// OMFI:ECCP:FilmKind
	ePropEccpHeader,						// OMFI:ECCP:Header
	ePropEccpStart,							// OMFI:ECCP:Start
	ePropEccpStartEC,						// OMFI:ECCP:StartEC
	ePropEdefBypass,						// OMFI:EDEF:Bypass
	ePropEdefEffectDescription,				// OMFI:EDEF:EffectDescription
	ePropEdefEffectID,						// OMFI:EDEF:EffectID
	ePropEdefEffectName,					// OMFI:EDEF:EffectName
	ePropEdefIsTimeWarp,					// OMFI:EDEF:IsTimeWarp
	ePropEffeAudioSuitePlugInBagOfBits,		// OMFI:EFFE:AudioSuitePlugInBagOfBits
	ePropEffeAvidPrivateEffectID,			// OMFI:EFFE:AvidPrivateEffectID
	ePropEffeBypassOverride,				// OMFI:EFFE:BypassOverride
	ePropEffeEffectKind,					// OMFI:EFFE:EffectKind
	ePropEffeEffectSlots,					// OMFI:EFFE:EffectSlots
	ePropEffeFinalRendering,				// OMFI:EFFE:FinalRendering
	ePropEffeMotionCtlOffsetMapAdjust,		// OMFI:EFFE:MotionCtlOffsetMapAdjust
	ePropEffeMultiBandEQ_FilterName,		// OMFI:EFFE:MultiBandEQ_FilterName
	ePropEffeMultiBandEQ_NumBands,			// OMFI:EFFE:MultiBandEQ_NumBands
	ePropEffeMultiBandEQ_Version,			// OMFI:EFFE:MultiBandEQ_Version
	ePropEffePanVolIsTrimGainEffect,		// OMFI:EFFE:PanVolIsTrimGainEffect
	ePropEffeTrackManTrackedParamSettings,	// OMFI:EFFE:TrackManTrackedParamSettings
	ePropEffeTrackManTrackedParamSlots,		// OMFI:EFFE:TrackManTrackedParamSlots
	ePropEffeTrackManTrackerDataSlots,		// OMFI:EFFE:TrackManTrackerDataSlots
	ePropEffeWorkingRendering,				// OMFI:EFFE:WorkingRendering
	ePropEqmbFilterName,					// OMFI:EQMB:FilterName
	ePropEqmbNumBands,						// OMFI:EQMB:NumBands
	ePropEqmbVersion,						// OMFI:EQMB:Version
	ePropEratInputEditRage,					// OMFI:ERAT:InputEditRage
	ePropEratInputEditRate,					// OMFI:ERAT:InputEditRate
	ePropEratInputOffset,					// OMFI:ERAT:InputOffset
	ePropEratInputSegment,					// OMFI:ERAT:InputSegment
	ePropEratResultOffset,					// OMFI:ERAT:ResultOffset
	ePropEsltArgID,							// OMFI:ESLT:ArgID
	ePropEsltArgValue,						// OMFI:ESLT:ArgValue
	ePropFlPathName,						// OMFI:FL:PathName
	ePropGfxaGraphicFX,						// OMFI:GFXA:GraphicFX
	ePropHeadBlobs,							// OMFI:HEAD:Blobs
	ePropHeadByteOrder,						// OMFI:HEAD:ByteOrder
	ePropHeadClassDictionary,				// OMFI:HEAD:ClassDictionary
	ePropHeadContOffsetAtClose,				// OMFI:HEAD:ContainerOffsetAtClose
	ePropHeadDefinitionObjects,				// OMFI:HEAD:DefinitionObjects
	ePropHeadDelBlobsSize,					// OMFI:HEAD:DelBlobsSize
	ePropHeadIdentificationList,			// OMFI:HEAD:IdentificationList
	ePropHeadLastModified,					// OMFI:HEAD:LastModified
	ePropHeadMediaData,						// OMFI:HEAD:MediaData
	ePropHeadMobs,							// OMFI:HEAD:Mobs
	ePropHeadNumDelMobs,					// OMFI:HEAD:NumDelMobs
	ePropHeadPrimaryMobs,					// OMFI:HEAD:PrimaryMobs
	ePropHeadTOCOffsetAtClose,				// OMFI:HEAD:TOCOffsetAtClose
	ePropHeadToolkitVersion,				// OMFI:HEAD:ToolkitVersion
	ePropHeadVersion,						// OMFI:HEAD:Version
	ePropIdatImageData,						// OMFI:IDAT:ImageData
	ePropIdatMobID,							// OMFI:IDAT:MobID
	ePropIdntCompanyName,					// OMFI:IDNT:CompanyName
	ePropIdntDate,							// OMFI:IDNT:Date
	ePropIdntIDByteOrder,					// OMFI:IDNT:IDByteOrder
	ePropIdntPlatform,						// OMFI:IDNT:Platform
	ePropIdntProductID,						// OMFI:IDNT:ProductID
	ePropIdntProductName,					// OMFI:IDNT:ProductName
	ePropIdntProductVersion,				// OMFI:IDNT:ProductVersion
	ePropIdntProductVersionString,			// OMFI:IDNT:ProductVersionString
	ePropIdntToolkitVersion,				// OMFI:IDNT:ToolkitVersion
	ePropJpedJPEDImageStartAlignment,		// OMFI:JPED:JPEDImageStartAlignment
	ePropJpedJPEGTag,						// OMFI:JPED:JPEGTag
	ePropJpedOffsetToFrameIndexes,			// OMFI:JPED:OffsetToFrameIndexes
	ePropJpedQntznTbl,						// OMFI:JPED:QntznTbl
	ePropJpedQntznTblLen,					// OMFI:JPED:QntznTblLen
	ePropJpedQuantizationTables,			// OMFI:JPED:QuantizationTables
	ePropJpegFrameIndex,					// OMFI:JPEG:FrameIndex
	ePropJpegFrameIndexExt,					// OMFI:JPEG:FrameIndexExt
	ePropJpegMobID,							// OMFI:JPEG:MobID
	ePropMacdUTF8CanonicalPathName,			// OMFI:MACD:UTF8CanonicalPathName
	ePropMacdlDirID,						// OMFI:MACDL:DirID
	ePropMacdlFileName,						// OMFI:MACDL:FileName
	ePropMacdlVRef,							// OMFI:MACDL:VRef
	ePropMaclDirID,							// OMFI:MACL:DirID
	ePropMaclFileName,						// OMFI:MACL:FileName
	ePropMaclPathName,						// OMFI:MACL:PathName
	ePropMaclSDSAddress,					// OMFI:MACL:SDSAddress
	ePropMaclSDSMobID,						// OMFI:MACL:SDSMobID
	ePropMaclVName,							// OMFI:MACL:VName
	ePropMaclVRef,							// OMFI:MACL:VRef
	ePropMaskIsDouble,						// OMFI:MASK:IsDouble
	ePropMaskMaskBits,						// OMFI:MASK:MaskBits
	ePropMcmrMobID,							// OMFI:MCMR:MobID
	ePropMcmrPosition,						// OMFI:MCMR:Position
	ePropMdatAudioData,						// OMFI:MDAT:AudioData
	ePropMdatData,							// OMFI:MDAT:Data
	ePropMdatImageData,						// OMFI:MDAT:ImageData
	ePropMdatMobID,							// OMFI:MDAT:MobID
	ePropMdauBytesPerSample,				// OMFI:MDAU:BytesPerSample
	ePropMdauClockDivisor,					// OMFI:MDAU:ClockDivisor
	ePropMdauClockRate,						// OMFI:MDAU:ClockRate
	ePropMdauNumberOfChannels,				// OMFI:MDAU:NumberOfChannels
	ePropMdauNumberOfSamples,				// OMFI:MDAU:NumberOfSamples
	ePropMdauPullDown,						// OMFI:MDAU:PullDown
	ePropMdesKitCodecDesc,					// OMFI:MDES:KitCodecDesc
	ePropMdesKitCodecID,					// OMFI:MDES:KitCodecID
	ePropMdesLocator,						// OMFI:MDES:Locator
	ePropMdesMobKind,						// OMFI:MDES:MobKind
	ePropMdfl64BitSupport,					// OMFI:MDFL:64BitSupport
	ePropMdfldataOffset,					// OMFI:MDFL:dataOffset
	ePropMdflIsOMFI,						// OMFI:MDFL:IsOMFI
	ePropMdflLength,						// OMFI:MDFL:Length
	ePropMdflSampleRate,					// OMFI:MDFL:SampleRate
	ePropMdfmFilmAspectRatio,				// OMFI:MDFM:FilmAspectRatio
	ePropMdfmFilmFormat,					// OMFI:MDFM:FilmFormat
	ePropMdfmFrameRate,						// OMFI:MDFM:FrameRate
	ePropMdfmManufacturer,					// OMFI:MDFM:Manufacturer
	ePropMdfmModel,							// OMFI:MDFM:Model
	ePropMdfmPerforationsPerFrame,			// OMFI:MDFM:PerforationsPerFrame
	ePropMdtpCFrame,						// OMFI:MDTP:CFrame
	ePropMdtpFormFactor,					// OMFI:MDTP:FormFactor
	ePropMdtpLength,						// OMFI:MDTP:Length
	ePropMdtpManufacturer,					// OMFI:MDTP:Manufacturer
	ePropMdtpModel,							// OMFI:MDTP:Model
	ePropMdtpTapeFormat,					// OMFI:MDTP:TapeFormat
	ePropMdtpTypeCaseType,					// OMFI:MDTP:TypeCaseType
	ePropMdtpVideoSignal,					// OMFI:MDTP:VideoSignal
	ePropMfmlLastKnownVolume,				// OMFI:MFML:LastKnownVolume
	ePropMfmlLinkUIDHigh,					// OMFI:MFML:LinkUIDHigh
	ePropMfmlLinkUIDLow,					// OMFI:MFML:LinkUIDLow
	ePropMfmlMobID,							// OMFI:MFML:MobID
	ePropMfmlTrackType,						// OMFI:MFML:TrackType
	ePropMgrpChoices,						// OMFI:MGRP:Choices
	ePropMgrpRepSetType,					// OMFI:MGRP:RepSetType
	ePropMgrpStillFrame,					// OMFI:MGRP:StillFrame
	ePropMobj_CreationTime,					// OMFI:MOBJ:_CreationTime
	ePropMobjAppCode,						// OMFI:MOBJ:AppCode
	ePropMobjCreationTime,					// OMFI:MOBJ:CreationTime
	ePropMobjLastModified,					// OMFI:MOBJ:LastModified
	ePropMobjMobID,							// OMFI:MOBJ:MobID
	ePropMobjMobType,						// OMFI:MOBJ:MobType
	ePropMobjName,							// OMFI:MOBJ:Name
	ePropMobjPhysicalMedia,					// OMFI:MOBJ:PhysicalMedia
	ePropMobjSlots,							// OMFI:MOBJ:Slots
	ePropMobjStartPosition,					// OMFI:MOBJ:StartPosition
	ePropMobjUsageCode,						// OMFI:MOBJ:UsageCode
	ePropMobjUserAttributes,				// OMFI:MOBJ:UserAttributes
	ePropMobrMobID,							// OMFI:MOBR:MobID
	ePropMobrPosition,						// OMFI:MOBR:Position
	ePropMpegFrameIndex,					// OMFI:MPEG:FrameIndex
	ePropMpegMPEGFrameIndex,				// OMFI:MPEG:MPEGFrameIndex
	ePropMpgaOrigin,						// OMFI:MPGA:Origin
	ePropMpgaSubframeAlignment,				// OMFI:MPGA:SubframeAlignment
	ePropMpgiBitRate,						// OMFI:MPGI:BitRate
	ePropMpgiGOPStructure,					// OMFI:MPGI:GOPStructure
	ePropMpgiImageStartAlignment,			// OMFI:MPGI:ImageStartAlignment
	ePropMpgiisMPEG1,						// OMFI:MPGI:isMPEG1
	ePropMpgiLeadingDiscard,				// OMFI:MPGI:LeadingDiscard
	ePropMpgiMaxGOP,						// OMFI:MPGI:MaxGOP
	ePropMpgiMinGOP,						// OMFI:MPGI:MinGOP
	ePropMpgiMPEGStreamType,				// OMFI:MPGI:MPEGStreamType
	ePropMpgiMPEGVersion,					// OMFI:MPGI:MPEGVersion
	ePropMpgiOffsetToFrameIndexes,			// OMFI:MPGI:OffsetToFrameIndexes
	ePropMpgiomMPGIAMEVersion,				// OMFI:MPGI:omMPGIAMEVersion
	ePropMpgiomMPGIMaxGOPLength,			// OMFI:MPGI:omMPGIMaxGOPLength
	ePropMpgiomMPGIMinGOPLength,			// OMFI:MPGI:omMPGIMinGOPLength
	ePropMpgiProfileAndLevel,				// OMFI:MPGI:ProfileAndLevel
	ePropMpgiRandomAccess,					// OMFI:MPGI:RandomAccess
	ePropMpgiSequenceHdr,					// OMFI:MPGI:SequenceHdr
	ePropMpgiSequenceHdrLen,				// OMFI:MPGI:SequenceHdrLen
	ePropMpgiStreamType,					// OMFI:MPGI:StreamType
	ePropMpgiTrailingDiscard,				// OMFI:MPGI:TrailingDiscard
	ePropMsltEditRate,						// OMFI:MSLT:EditRate
	ePropMsltSegment,						// OMFI:MSLT:Segment
	ePropMsltTrackDesc,						// OMFI:MSLT:TrackDesc
	ePropMsmlAMEVersion,					// OMFI:MSML:AMEVersion
	ePropMsmlDomainType,					// OMFI:MSML:DomainType
	ePropMsmlLastKnownVolume,				// OMFI:MSML:LastKnownVolume
	ePropMsmlMobID,							// OMFI:MSML:MobID
	ePropNestSlots,							// OMFI:NEST:Slots
	ePropNetlURLString,						// OMFI:NETL:URLString
	ePropOobjObjClass,						// OMFI:OOBJ:ObjClass
	ePropPcmaAudioCodingFormat,				// OMFI:PCMA:AudioCodingFormat
	ePropPcmaAudioRefLevel,					// OMFI:PCMA:AudioRefLevel
	ePropPcmaAudioSamplingRate,				// OMFI:PCMA:AudioSamplingRate
	ePropPcmaAverageBytesPerSecond,			// OMFI:PCMA:AverageBytesPerSecond
	ePropPcmaBlockAlignment,				// OMFI:PCMA:BlockAlignment
	ePropPcmaDialNorm,						// OMFI:PCMA:DialNorm
	ePropPcmaElectroSpatialFormulation,		// OMFI:PCMA:ElectroSpatialFormulation
	ePropPcmaHasPeakEnvelopeData,			// OMFI:PCMA:HasPeakEnvelopeData
	ePropPcmaLocked,						// OMFI:PCMA:Locked
	ePropPcmaPeakChannelCount,				// OMFI:PCMA:PeakChannelCount
	ePropPcmaPeakEnvelopeBlockSize,			// OMFI:PCMA:PeakEnvelopeBlockSize
	ePropPcmaPeakEnvelopeData,				// OMFI:PCMA:PeakEnvelopeData
	ePropPcmaPeakEnvelopeFormat,			// OMFI:PCMA:PeakEnvelopeFormat
	ePropPcmaPeakEnvelopeTimestamp,			// OMFI:PCMA:PeakEnvelopeTimestamp
	ePropPcmaPeakEnvelopeVersion,			// OMFI:PCMA:PeakEnvelopeVersion
	ePropPcmaPeakFrameCount,				// OMFI:PCMA:PeakFrameCount
	ePropPcmaPeakOfPeaksOffset,				// OMFI:PCMA:PeakOfPeaksOffset
	ePropPcmaPointsPerPeakValue,			// OMFI:PCMA:PointsPerPeakValue
	ePropPcmaSequenceOffset,				// OMFI:PCMA:SequenceOffset
	ePropPdwnInputSegment,					// OMFI:PDWN:InputSegment
	ePropPdwnPulldownDirection,				// OMFI:PDWN:PulldownDirection
	ePropPdwnPulldownKind,					// OMFI:PDWN:PulldownKind
	ePropPdwnPulldownPhaseFrame,			// OMFI:PDWN:PulldownPhaseFrame
	ePropPrclExtrapKind,					// OMFI:PRCL:ExtrapKind
	ePropPrclFields,						// OMFI:PRCL:Fields
	ePropPtppDataKind,						// OMFI:PTPP:DataKind
	ePropPtppPropertyID,					// OMFI:PTPP:PropertyID
	ePropPtppValue,							// OMFI:PTPP:Value
	ePropQtmdfType,							// OMFI:QTMD:fType
	ePropRgbaPalette,						// OMFI:RGBA:Palette
	ePropRgbaPaletteLayout,					// OMFI:RGBA:PaletteLayout
	ePropRgbaPaletteLayoutSize,				// OMFI:RGBA:PaletteLayoutSize
	ePropRgbaPaletteSize,					// OMFI:RGBA:PaletteSize
	ePropRgbaPaletteStructure,				// OMFI:RGBA:PaletteStructure
	ePropRgbaPaletteStructureSize,			// OMFI:RGBA:PaletteStructureSize
	ePropRgbaPixelLayout,					// OMFI:RGBA:PixelLayout
	ePropRgbaPixelLayoutSize,				// OMFI:RGBA:PixelLayoutSize
	ePropRgbaPixelStructure,				// OMFI:RGBA:PixelStructure
	ePropRgbaPixelStructureSize,			// OMFI:RGBA:PixelStructureSize
	ePropRledFrameIndex,					// OMFI:RLED:FrameIndex
	ePropRledOffsetToFrameIndexes,			// OMFI:RLED:OffsetToFrameIndexes
	ePropSclpFadeInLength,					// OMFI:SCLP:FadeInLength
	ePropSclpFadeInType,					// OMFI:SCLP:FadeInType
	ePropSclpFadeOutLength,					// OMFI:SCLP:FadeOutLength
	ePropSclpFadeOutType,					// OMFI:SCLP:FadeOutType
	ePropSclpMobID,							// OMFI:SCLP:MobID
	ePropSclpSourceID,						// OMFI:SCLP:SourceID
	ePropSclpSourcePosition,				// OMFI:SCLP:SourcePosition
	ePropSclpSourceTrack,					// OMFI:SCLP:SourceTrack
	ePropSclpSourceTrackID,					// OMFI:SCLP:SourceTrackID
	ePropSclpStartTime,						// OMFI:SCLP:StartTime
	ePropSd2dBitsPerSample,					// OMFI:SD2D:BitsPerSample
	ePropSd2dNumOfChannels,					// OMFI:SD2D:NumOfChannels
	ePropSd2mAudioData,						// OMFI:SD2M:AudioData
	ePropSd2mData,							// OMFI:SD2M:Data
	ePropSd2mMobID,							// OMFI:SD2M:MobID
	ePropSddBitsPerSample,					// OMFI:SDD:BitsPerSample
	ePropSddData,							// OMFI:SDD:Data
	ePropSddMobID,							// OMFI:SDD:MobID
	ePropSddNumChannels,					// OMFI:SDD:NumChannels
	ePropSddNumOfChannels,					// OMFI:SDD:NumOfChannels
	ePropSequComponents,					// OMFI:SEQU:Components
	ePropSequSequence,						// OMFI:SEQU:Sequence
	ePropSlctAlternates,					// OMFI:SLCT:Alternates
	ePropSlctIsGanged,						// OMFI:SLCT:IsGanged
	ePropSlctSelected,						// OMFI:SLCT:Selected
	ePropSlctSelectedTrack,					// OMFI:SLCT:SelectedTrack
	ePropSmobMediaDescription,				// OMFI:SMOB:MediaDescription
	ePropSpedDenominator,					// OMFI:SPED:Denominator
	ePropSpedIsFreezeFrame,					// OMFI:SPED:IsFreezeFrame
	ePropSpedNumerator,						// OMFI:SPED:Numerator
	ePropSrefRelativeScope,					// OMFI:SREF:RelativeScope
	ePropSrefRelativeSlot,					// OMFI:SREF:RelativeSlot
	ePropTccpDrop,							// OMFI:TCCP:Drop
	ePropTccpFlags,							// OMFI:TCCP:Flags
	ePropTccpFPS,							// OMFI:TCCP:FPS
	ePropTccpStart,							// OMFI:TCCP:Start
	ePropTccpStartTC,						// OMFI:TCCP:StartTC
	ePropTifdBufLen,						// OMFI:TIFD:BufLen
	ePropTifdFirstIFD,						// OMFI:TIFD:FirstIFD
	ePropTifdFP16QTables,					// OMFI:TIFD:FP16QTables
	ePropTifdIsContiguous,					// OMFI:TIFD:IsContiguous
	ePropTifdIsUniform,						// OMFI:TIFD:IsUniform
	ePropTifdJPEGTableID,					// OMFI:TIFD:JPEGTableID
	ePropTifdLeadingLines,					// OMFI:TIFD:LeadingLines
	ePropTifdRLEDesc,						// OMFI:TIFD:RLEDesc
	ePropTifdSummary,						// OMFI:TIFD:Summary
	ePropTifdTrailingLines,					// OMFI:TIFD:TrailingLines
	ePropTifdUncompDesc,					// OMFI:TIFD:UncompDesc
	ePropTifdUniformness,					// OMFI:TIFD:Uniformness
											// OMFI:TIFF:Data
	ePropTiffImageData,						// OMFI:TIFF:ImageData
	ePropTiffMobID,							// OMFI:TIFF:MobID
	ePropTmtdParameterSlots,				// OMFI:TMTD:ParameterSlots
	ePropTmtdSettings,						// OMFI:TMTD:Settings
	ePropTmtpSettings,						// OMFI:TMTP:Settings
	ePropTnfxTrackMan,						// OMFI:TNFX:TrackMan
	ePropTrakAttributes,					// OMFI:TRAK:Attributes
	ePropTrakBob,							// OMFI:TRAK:Bob
	ePropTrakFillerProxy,					// OMFI:TRAK:FillerProxy
	ePropTrakLabelNumber,					// OMFI:TRAK:LabelNumber
	ePropTrakOptFlags,						// OMFI:TRAK:OptFlags
	ePropTrakSessionAttrs,					// OMFI:TRAK:SessionAttrs
	ePropTrakTrackComponent,				// OMFI:TRAK:TrackComponent
	ePropTranCutPoint,						// OMFI:TRAN:CutPoint
	ePropTranEffect,						// OMFI:TRAN:Effect
	ePropTrkdLockNumber,					// OMFI:TRKD:LockNumber
	ePropTrkdOrigin,						// OMFI:TRKD:Origin
	ePropTrkdPhysicalTrack,					// OMFI:TRKD:PhysicalTrack
	ePropTrkdTrackID,						// OMFI:TRKD:TrackID
	ePropTrkdTrackName,						// OMFI:TRKD:TrackName
	ePropTrkgGroupLength,					// OMFI:TRKG:GroupLength
	ePropTrkgLockNumber,					// OMFI:TRKG:LockNumber	// No such thing. Typo. My bad. Remove this. I meant OMFI:TRKD:LockNumber
	ePropTrkgTracks,						// OMFI:TRKG:Tracks
	ePropTrkrRelativeScope,					// OMFI:TRKR:RelativeScope
	ePropTrkrRelativeTrack,					// OMFI:TRKR:RelativeTrack
	ePropTxtlName,							// OMFI:TXTL:Name
	ePropTxtlVersion,						// OMFI:TXTL:Version
	ePropUnxdlPathName,						// OMFI:UNXDL:PathName
	ePropUnxlPathName,						// OMFI:UNXL:PathName
	ePropVvalExtrapolation,					// OMFI:VVAL:Extrapolation
	ePropVvalFieldCount,					// OMFI:VVAL:FieldCount
	ePropVvalInterpolation,					// OMFI:VVAL:Interpolation
	ePropVvalParameterID,					// OMFI:VVAL:ParameterID
	ePropVvalPointList,						// OMFI:VVAL:PointList
	ePropWarpEditRate,						// OMFI:WARP:EditRate
	ePropWarpPhaseOffset,					// OMFI:WARP:PhaseOffset
	ePropWavdSummary,						// OMFI:WAVD:Summary
	ePropWaveAudioData,						// OMFI:WAVE:AudioData
	ePropWaveData,							// OMFI:WAVE:Data
	ePropWaveMobID,							// OMFI:WAVE:MobID
	ePropWinlFullPathName,					// OMFI:WINL:FullPathName
	ePropWinlPathName,						// OMFI:WINL:PathName
	ePropWinlShortcut,						// OMFI:WINL:Shortcut
	eMaxProperty
};

//	OMF Data Types.
enum DataTypeOrdinal
{
	eTypeNoType,				// omfi:NoType
	eTypeArgIDType,				// omfi:ArgIDType
	eTypeAttrKind,				// omfi:AttrKind
	eTypeBoolean,				// omfi:Boolean
	eTypeChar,					// omfi:Char
	eTypeCharSetType,			// omfi:CharSetType
	eTypeClassID,				// omfi:ClassID
	eTypeColorSitingType,		// omfi:ColorSitingType
	eTypeColorSpace,			// omfi:ColorSpace
	eTypeCompCodeArray,			// omfi:CompCodeArray
	eTypeCompSizeArray,			// omfi:CompSizeArray
	eTypeDataValue,				// omfi:DataValue
	eTypeDirectionCode,			// omfi:DirectionCode
	eTypeDouble,				// omfi:Double
	eTypeEdgeType,				// omfi:EdgeType
	eTypeEditHintType,			// omfi:EditHintType
	eTypeExactEditRate,			// omfi:ExactEditRate
	eTypeExtrapKind,			// omfi:ExtrapKind
	eTypeFadeType,				// omfi:FadeType
	eTypeFilmType,				// omfi:FilmType
	eTypeGUID,					// omfi:GUID
	eTypeInt8,					// omfi:Int8
	eTypeInt16,					// omfi:Int16
	eTypeInt32,					// omfi:Int32
	eTypeInt64,					// omfi:Int64
	eTypeInt32Array,			// omfi:Int32Array
	eTypeInt64Array,			// omfi:Int64Array
	eTypeInterpKind,			// omfi:InterpKind
	eTypeJPEGTableIDType,		// omfi:JPEGTableIDType
	eTypeLayoutType,			// omfi:LayoutType
	eTypeLength32,				// omfi:Length32
	eTypeLength64,				// omfi:Length64
	eTypeLong,					// omfi:Long
	eTypeMobIndex,				// omfi:MobIndex
	eTypeObjectTag,				// omfi:ObjectTag
	eTypeObjRef,				// omfi:ObjRef
	eTypeObjRefArray,			// omfi:ObjRefArray
	eTypePhaseFrameType,		// omfi:PhaseFrameType
	eTypePhysicalMobType,		// omfi:PhysicalMobType
	eTypePosition32,			// omfi:Position32
	eTypePosition32Array,		// omfi:Position32Array
	eTypePosition64,			// omfi:Position64
	eTypePosition64Array,		// omfi:Position64Array
	eTypeProductVersion,		// omfi:ProductVersion
	eTypePulldownDirectionType,	// omfi:PulldownDirectionType
	eTypePulldownKindType,		// omfi:PulldownKindType
	eTypeRational,				// omfi:Rational
	eTypeShort,					// omfi:Short
	eTypeString,				// omfi:String
	eTypeTapeCaseType,			// omfi:TapeCaseType
	eTypeTapeFormatType,		// omfi:TapeFormatType
	eTypeTimeStamp,				// omfi:TimeStamp
	eTypeTrackType,				// omfi:TrackType
	eTypeUchar,					// omfi:Uchar
	eTypeUID,					// omfi:UID
	eTypeUInt8,					// omfi:UInt8
	eTypeUInt16,				// omfi:UInt16
	eTypeUInt32,				// omfi:UInt32
	eTypeUInt64,				// omfi:UInt64
	eTypeUlong,					// omfi:Ulong
	eTypeUniqueName,			// omfi:UniqueName
	eTypeUsageCodeType,			// omfi:UsageCodeType
	eTypeUshort,				// omfi:Ushort
	eTypeVarLenBytes,			// omfi:VarLenBytes
	eTypeVersionType,			// omfi:VersionType
	eTypeVideoSignalType,		// omfi:VideoSignalType
	eMaxDataType
};

//	OMF Data Kinds.
enum DataKindOrdinal {
	eKindNoDatakind,		// omfi:data:NoDatakind
	eKindPicture,			// omfi:data:Picture
	eKindSound,				// omfi:data:Sound
	eKindTimecode,			// omfi:data:Timecode
	eKindEdgecode,			// omfi:data:Edgecode
	eKindUSERATTR,			// omfi:data:USERATTR
	eKindEFFECTDATA,		// omfi:data:EFFECTDATA
	eKindMARKER,			// omfi:data:MARKER
	eKindStereoSound,		// omfi:data:StereoSound
	eKindCONTROL,			// omfi:data:CONTROL
	eKindString,			// omfi:data:String
	eKindMIDI,				// omfi:data:MIDI
	eKindMETA,				// omfi:data:META
	eKindAudioEQBand,		// omfi:data:AudioEQBand
	eKindColor,				// omfi:data:Color
	eKindColorSpace,		// omfi:data:ColorSpace
	eKindDirectionCode,		// omfi:data:DirectionCode
	eKindDistance,			// omfi:data:Distance
	eKindEffectGlobals,		// omfi:data:EffectGlobals
	eKindEffectGlobalsExt,	// omfi:data:EffectGlobalsExt
	eKindBoolean,			// omfi:data:Boolean
	eKindChar,				// omfi:data:Char
	eKindInt8,				// omfi:data:Int8
	eKindInt16,				// omfi:data:Int16
	eKindInt32,				// omfi:data:Int32
	eKindInt64,				// omfi:data:Int64
	eKindUInt8,				// omfi:data:UInt8
	eKindUInt16,			// omfi:data:UInt16
	eKindUInt32,			// omfi:data:UInt32
	eKindUInt64,			// omfi:data:UInt64
	eKindKeyFrame,			// omfi:data:KeyFrame
	eKindMatte,				// omfi:data:Matte
	eKindPictureWithMatte,	// omfi:data:PictureWithMatte
	eKindPoint,				// omfi:data:Point
	eKindPolynomial,		// omfi:data:Polynomial
	eKindRational,			// omfi:data:Rational
	eKindUserParam,			// omfi:data:UserParam
	eKindINVALID,			// omfi:data:INVALID
	eMaxDataKind
};

//	OMF Effect ID strings.
enum EffectOrdinal {
	eEffectMonoAudioGain,			// omfi:effect:MonoAudioGain
	eEffectMonoAudioMixdown,		// omfi:effect:MonoAudioMixdown
	eEffectMonoAudioPan,			// omfi:effect:MonoAudioPan
	eEffectSimpleMonoAudioDissolve,	// omfi:effect:SimpleMonoAudioDissolve
	eEffectSimpleVideoDissolve,		// omfi:effect:SimpleVideoDissolve
	eEffectSMPTEVideoWipe,			// omfi:effect:SMPTEVideoWipe
	eEffectVideoFadeToBlack,		// omfi:effect:VideoFadeToBlack
	eEffectVideoFrameMask,			// omfi:effect:VideoFrameMask
	eEffectVideoRepeat,				// omfi:effect:VideoRepeat
	eEffectVideoSpeedControl,		// omfi:effect:VideoSpeedControl
	eMaxEffectIDString
};

};
